11-21 17:00:04 jdbc[2]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-168]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:172)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:92)
	at org.h2.Driver.connect(Driver.java:72)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:806)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$100(DatabaseConnection.java:98)
	at org.netbeans.modules.db.explorer.DatabaseConnection$2.run(DatabaseConnection.java:872)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
11-21 23:02:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:585)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:224)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:321)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
11-21 23:02:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:585)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:188)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:322)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
11-21 23:02:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:585)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:191)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:107)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:206)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
11-22 13:01:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO BOOXTORE.""PUBLIC"".LIVRE (ID_CATEGORIE, TITRE, DATE_PARUTION, RESUME, SOMMAIRE, QUANTITER_DISPONIBLE, AUTEUR, EDITEUR, PRIX, ETAT) 
	VALUES (8, 'Les aventures d''A. au pays des merveilles', '2006-07-20', 'velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris', 'felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum.', 83, 'Lewis Caroll', 'Syros', 19.166, NULL)
INSERT[*] INTO BOOXTORE.""PUBLIC"".LIVRE (ID_CATEGORIE, TITRE, DATE_PARUTION, RESUME, SOMMAIRE, QUANTITER_DISPONIBLE, AUTEUR, EDITEUR, PRIX, ETAT) 
	VALUES (4, 'Une vie de chien', '2010-08-31', 'nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit', 'ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor', 59, 'Leydier Michel', 'Gautier-Languereau', 19.177, 'Neuf')"; SQL statement:
INSERT INTO BOOXTORE."PUBLIC".LIVRE (ID_CATEGORIE, TITRE, DATE_PARUTION, RESUME, SOMMAIRE, QUANTITER_DISPONIBLE, AUTEUR, EDITEUR, PRIX, ETAT) 
	VALUES (8, 'Les aventures d''A. au pays des merveilles', '2006-07-20', 'velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris', 'felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum.', 83, 'Lewis Caroll', 'Syros', 19.166, NULL)
INSERT INTO BOOXTORE."PUBLIC".LIVRE (ID_CATEGORIE, TITRE, DATE_PARUTION, RESUME, SOMMAIRE, QUANTITER_DISPONIBLE, AUTEUR, EDITEUR, PRIX, ETAT) 
	VALUES (4, 'Une vie de chien', '2010-08-31', 'nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit', 'ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor', 59, 'Leydier Michel', 'Gautier-Languereau', 19.177, 'Neuf') [42000-168]
11-22 13:13:16 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:585)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:224)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:321)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
11-22 13:13:16 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:585)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:188)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:322)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
11-22 13:13:16 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1381)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1359)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:585)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:191)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:107)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:206)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
11-22 13:15:42 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: ; SQL statement:
ALTER TABLE CLIENT ADD COLUMN TYPE_COMPTE [50004-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3654)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3517)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:4982)
	at org.h2.command.Parser.parseAlterTable(Parser.java:4827)
	at org.h2.command.Parser.parseAlter(Parser.java:4315)
	at org.h2.command.Parser.parsePrepared(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.executeSQLStatement(SQLExecutionHelper.java:607)
	at org.netbeans.modules.db.dataview.output.SQLExecutionHelper.initialDataLoad(SQLExecutionHelper.java:114)
	at org.netbeans.modules.db.dataview.output.DataView.create(DataView.java:105)
	at org.netbeans.modules.db.dataview.api.DataView.create(DataView.java:74)
	at org.netbeans.modules.db.sql.execute.SQLExecuteHelper.execute(SQLExecuteHelper.java:116)
	at org.netbeans.modules.db.sql.loader.SQLEditorSupport$SQLExecutor.run(SQLEditorSupport.java:564)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
